name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.x, 7.x, 8.x, 9.x, 10.x, 11.x, 12.x, 13.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install request
      - run: npm install
      - run: npm test
  
  
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run unit tests with coverage
      run: npm test -v -race -coverprofile=coverage.txt
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        file: coverage.txt
        flags: UnitTests
        verbose: true
        fail_ci_if_error: false
